### ISSUE TITLE
Huge MS 

### ISSUE THREAD

**Issue by vicciusomerta** [overextended/qtarget#25]
![image](https://user-images.githubusercontent.com/28043209/140033493-5c6ee68a-7c07-4fad-8f71-e1d6a7a356a0.png)
How can i solve this ? 4.15 ms and if i leave it like that it goes to 7ms , if i restart it goes to 0.1ms, I added > restart qtarget in my cfg but i doesn't work, i have to do it manually everytime i join the server, i haven't modified anything from it.
 Thanks.

**Comment by thelindat** [comment]
Are you loading a bunch of polyzones in debug mode?

**Comment by vicciusomerta** [comment]
Hi Linden, thank you for the input !  yea, i had them on, now is 0.30+ ms, but if i restart it  it goes back to 0.01 ms not sure what's causing that ms.

**Comment by thelindat** [comment]
I suggest looking through all your resources that utilise qtarget and seeing what is loading debug data; the ms drops to normal because there's no PolyZones anymore.
