### ISSUE TITLE
Not opening

### ISSUE THREAD

**Issue by Zykem** [overextended/qtarget#29]
I uploaded the dependency, and the script. I click left alt and the eye does not pop up.

**Comment by Steviol** [comment]
yup this happens to me too, some player didnt pop up eye target. tried to reinstall fivem but it seems not solved

**Comment by thelindat** [comment]
Nothing I can do with zero information and no way to reproduce it.

**Comment by Steviol** [comment]
solved by this https://www.youtube.com/watch?v=AeQpeEUZkRs&ab_channel=PROJECTROGUEROLEPLAY, it seems fivem bug where keybind is stuck? idk whats going on

**Comment by thelindat** [comment]
> solved by this https://www.youtube.com/watch?v=AeQpeEUZkRs&ab_channel=PROJECTROGUEROLEPLAY, it seems fivem bug where keybind is stuck? idk whats going on

https://github.com/citizenfx/fivem/issues/935

If you're using dumb obfuscator shit like choco does then it may be related, but who knows. Not a qtarget issue.
