### ISSUE TITLE
RemoveTargetEntity not functioning

### ISSUE THREAD

**Issue by Adzeiros** [overextended/qtarget#32]
Been using qTarget for a while now,

I am adding targets onto a vehicle, and wish to remove the target after it's called (So it cannot be spammed)

Here is the code for adding the target:

```
exports.qtarget:AddTargetEntity(car, {
      options = {
        {
          event = "repWheel",
          icon = "fas fa-wrench",
          label = "Repair Wheel",
          num = 1
        }
      },
      distance = 1.0
    })
```

And here is the function `repWheel` where I attempt to remove the target:

```
AddEventHandler('repWheel', function()
  exports.qtarget:RemoveTargetEntity({'Repair Wheel'})
end)
```

Here is the error message in the console:

```
SCRIPT ERROR: Invalid Lua type in __data
> NetworkGetEntityIsNetworked (NetworkGetEntityIsNetworked.lua:3)
> ref (@qtarget/client/main.lua:365)
> handler (@scriptName/client/client.lua:536)
> fn (@qtarget/client/main.lua:267)
```

Any ideas would be great, I do not wish to use box zones as they would be very tedious to set up for each part.

**Comment by thelindat** [comment]
![image](https://user-images.githubusercontent.com/65407488/142752396-7ba1fd2d-97b1-42dc-9e92-7446fd55dd23.png)
How do you expect to remove an option from a non-specified entity? You're passing the value to remove and not what to remove it from.

**Comment by Adzeiros** [comment]
First off, this is an entity target and not a model target...

Secondly, according to the documentation, you must specify the label names alone to remove them.

```
Options can be removed by calling the remove export, with all labels as entries in an array.

exports.qtarget:RemoveTargetEntity({
	'action 1', 'action 2'
})
```

Here is the export inside the qtarget code:

```
RemoveTargetEntity = function(entity, labels)
	local entity = NetworkGetEntityIsNetworked(entity) and NetworkGetNetworkIdFromEntity(entity) or false
	if entity then
		for k, v in pairs(labels) do
			if Entities[entity] then
				Entities[entity][v] = nil
			end
		end
	end
end
exports("RemoveTargetEntity", RemoveTargetEntity)
```

As you can see, the actual export function only accepts 1 parameter, not 2... So even if I wanted to pass both the entity and the labels I cannot... I can change this obviously, but I wish to make this issue known to the creator...

**Comment by thelindat** [comment]
Then the issue is in the documentation which only lists the labels and not the entity.

> the actual export function only accepts 1 parameter, not 2
The function very clearly takes two arguments (entity, and labels).
```lua
exports.qtarget:RemoveTargetEntity(car, {'Repair Wheel'})
```

**Comment by Adzeiros** [comment]
Yes, I did change my post...

The only thing I wish for them to do is fix the public documentation so people dont need to dig through the code...

So I would ask that you do not close issues that are not resolved...

Thank you...

**Comment by thelindat** [comment]
Looks pretty resolved to me, and looking at code is usually a good idea when people want to utilise a resource; either because you can learn more, improve on it, or find mistakes. 

The mistake is in the documentation, which anybody is free to fix if I don’t personally get to it before that (more important things); regardless the second part of your reply says the export accepts a single argument only, which is incorrect - it exports the function defined above, which takes the entity and labels to remove.

qtarget is in need of a lot of work, especially the documentation, but had been abandoned for some time due to the other developer leaving FiveM, my own lack of interest and other projects taking precedence.
