### ISSUE TITLE
using canInteract to only show option when hovering over specific vehicle part

### ISSUE THREAD

**Issue by Adzeiros** [overextended/qtarget#33]
I have noticed in the code of qTarget that there is an option to use canInteract to target specific parts/bones of the vehicle...

As you can see here:

```
canInteract = function(entity)
				return GetEntityBoneIndexByName(entity, 'door_dside_r') ~= -1
			end
```

However, when I attempt to use this in my own qtarget function it does not work.  Is this something that is possible to do?

Example:
```
exports.qtarget:AddTargetEntity(car, {
      options = {
        {
          event = "repWheel",
          icon = "fas fa-wrench",
          label = "Repair Wheel",
          num = 1,
          canInteract = function(entity)
                    return GetEntityBoneIndexByName(entity, 'wheel_rr') ~= -1
              end
        }
      },
      distance = 1.0
    })
```

I have attempted to do this but it seems that it always shows no matter where I look on the car... If it is not possible then that's fine.

**Comment by thelindat** [comment]
![image](https://user-images.githubusercontent.com/65407488/142752469-c4e86df7-85f9-4065-be6f-ef3349397afa.png)
