### ISSUE TITLE
Remove Target Entity working entirely without issue, but has documentation issues as pointed out in the previous issue by the resource maintainer, who has already put it on a todo list and does not require additional messages about said documentation issue

### ISSUE THREAD

**Issue by Adzeiros** [overextended/qtarget#34]
**First off, let me try this again, and hopefully my issue will be read to its full extent before someone closes it**

Been using qTarget for a while now,

I am adding targets onto a vehicle, and wish to remove the target after it's called (So it cannot be spammed)

Here is the code for adding the target:

```
exports.qtarget:AddTargetEntity(car, {
      options = {
        {
          event = "repWheel",
          icon = "fas fa-wrench",
          label = "Repair Wheel",
          num = 1
        }
      },
      distance = 1.0
    })
```

And here is the function repWheel where I attempt to remove the target:

```
AddEventHandler('repWheel', function()
  exports.qtarget:RemoveTargetEntity({'Repair Wheel'})
end)
```

Here is the error message in the console:

```
SCRIPT ERROR: Invalid Lua type in __data
> NetworkGetEntityIsNetworked (NetworkGetEntityIsNetworked.lua:3)
> ref (@qtarget/client/main.lua:365)
> handler (@scriptName/client/client.lua:536)
> fn (@qtarget/client/main.lua:267)
```

according to the documentation, you must specify the label names alone to remove them.

```
Options can be removed by calling the remove export, with all labels as entries in an array.

exports.qtarget:RemoveTargetEntity({
	'action 1', 'action 2'
})
```

Here is the export inside the qtarget code:

```
RemoveTargetEntity = function(entity, labels)
	local entity = NetworkGetEntityIsNetworked(entity) and NetworkGetNetworkIdFromEntity(entity) or false
	if entity then
		for k, v in pairs(labels) do
			if Entities[entity] then
				Entities[entity][v] = nil
			end
		end
	end
end
exports("RemoveTargetEntity", RemoveTargetEntity)
```

As you can see, the actual function takes both the entity and the labels... So I wish to let the creator know that the documentation should be updated to show that...

-EDIT-

The documentation should be changed to reflect what is actually needed when removing an entity target:

`exports.qtarget:RemoveTargetEntity(entity, {'Label 1', 'Label 2'})`

**Comment by thelindat** [comment]
Docs are updated.
