### ISSUE TITLE
Issue with multiple actions

### ISSUE THREAD

**Issue by benzon** [overextended/qtarget#36]
So i played around with qTarget got a exports.qtarget:Ped({ 

I then had a box zone qtarget to, on a specific ped, until i removed the other qTarget on Ped's i would not get the box zone options i would only get the ped options, it's like it overwrighting or taking charge, aint there a way where it could acctually show both options insted of only showing that one option ?

**Comment by thelindat** [comment]
Support for adding options from multiple types (polyzone, generic, entity) would be nice, but requires a bit of a rework so don't expect anything soon.

**Comment by benzon** [comment]
Okay, it would be nice tho, since right now it can get abit iffy ad times.

I understand that it requires a rework with out doubt.

**Comment by JiminyKroket** [comment]
Fixed in latest PR?

**Comment by thelindat** [comment]
> Fixed in latest PR?

Different issue; basically if you find options at any point, you won't get to see additional options from other checks.

i.e. a generic ped check, model check, and netid check are all incompatible; you will only see one set of options.

**Comment by JiminyKroket** [comment]
I understand now

**Comment by JiminyKroket** [comment]
> Fixed in latest PR?

I say again?

**Comment by BerkieBb** [comment]
> > Fixed in latest PR?
> 
> I say again?

Still not

**Comment by BerkieBb** [comment]
@JiminyKroket were you going to make a new pull request from your original one, or do you want me to figure out how to fix this issue?

**Comment by JiminyKroket** [comment]
I have no current plans to update to 2.0 myself. I will not be able to attempt a new PR

**Comment by itsfaizy** [comment]
bump

**Comment by thelindat** [comment]
This issue will never be resolved in qtarget since the necessary changes are too frustrating to work into the existing code.
[ox_target](https://github.com/overextended/ox_target) is being developed to replace qtarget and solve my frustrations with it.
