### ISSUE TITLE
Vehicle Bones Problem

### ISSUE THREAD

**Issue by LoRDWiZz** [overextended/qtarget#45]
Hi I have one problem.. When I press ALT - https://streamable.com/hb4e6r. How to fix?

**Comment by mortalkiller** [comment]
Is this something that happens with all kind of vehicles?

**Comment by mortalkiller** [comment]
> Hi I have one problem.. When I press ALT - https://streamable.com/hb4e6r. How to fix?

The fix for this is in https://github.com/overextended/qtarget/pull/47
