### ISSUE TITLE
Eye blinking

### ISSUE THREAD

**Issue by wolvherin78** [overextended/qtarget#50]
When I select the target, the eye starts blinking repeatedly

**Comment by mortalkiller** [comment]
> When I select the target, the eye starts blinking repeatedly

@wolvherin78 I think this is already solved, try to download the latest version and check.

**Comment by wolvherin78** [comment]
> > When I select the target, the eye starts blinking repeatedly
> 
> @wolvherin78 I think this is already solved, try to download the latest version and check.

i have alredy last version 1.2.0

**Comment by thelindat** [comment]
> @mortalkiller i have alredy last version (release) 1.2.0 and use addTargetModel

1.2.0 was from August, everything changed since was still in development and just released as 2.0.0
