### ISSUE TITLE
Problem with job grades

### ISSUE THREAD

**Issue by LoRDWiZz** [overextended/qtarget#51]
After I add job and grade, eye don't work.

**Comment by thelindat** [comment]
eye do work
how about info
no?

**Comment by LoRDWiZz** [comment]
after adding a grade and pointing the eye to the poly zone, options don't show and the eye freezes

**Comment by thelindat** [comment]
Then you've set it up incorrectly.

**Comment by LoRDWiZz** [comment]
![Screenshot_20211227-211833_QLUA](https://user-images.githubusercontent.com/66243394/147501087-fba50f01-9970-4481-9ce8-94fe162eba46.jpg)

I think everything is correct?

**Comment by BerkieBb** [comment]
That `type` you have there is irrelevant for qtarget, that's something from qb-target

**Comment by LoRDWiZz** [comment]
When I put only job it works, but when I add and grade it doesn't work

**Comment by thelindat** [comment]
What framework?

**Comment by LoRDWiZz** [comment]
QB

**Comment by LoRDWiZz** [comment]
I fix the problem ... Here **PlayerData.job.grade** must be **PlayerData.job.grade.level**

**Comment by thelindat** [comment]
> I fix the problem ... In init.lua 118 row, where **PlayerData.job.grade** must be **PlayerData.job.grade.level**

I don't use QB so I'm not going to notice such things (supports there but I assumed people would use qb-target). I've commited your fix; thanks.

**Comment by BerkieBb** [comment]
> > I fix the problem ... In init.lua 118 row, where **PlayerData.job.grade** must be **PlayerData.job.grade.level**
> 
> I don't use QB so I'm not going to notice such things (supports there but I assumed people would use qb-target). I've commited your fix; thanks.

I'm going to pr those fixes for you once I'm back from vacation
