### ISSUE TITLE
excport erros from qtarget

### ISSUE THREAD

**Issue by DevMarley** [overextended/qtarget#56]
sup, I’m having this error in a script that I have in my server, I have the export and your script even comes with it, is there any error in this export?
![imagem](https://user-images.githubusercontent.com/36583733/149014026-b0a86264-cb69-4289-b271-e8bbf02a67aa.png)

scripts load order is okey
all its fine tbh

**Comment by BerkieBb** [comment]
Carro isn't an export in qtarget

**Comment by DevMarley** [comment]
i change for a test  but defualt is Vehicle

**Comment by DevMarley** [comment]
![imagem](https://user-images.githubusercontent.com/36583733/149025289-84d1aa40-ff17-411e-ad91-c02c56d34691.png)
 i think is all right..

**Comment by DevMarley** [comment]
?

**Comment by BerkieBb** [comment]
Change it back to Vehicle in that script
