### ISSUE TITLE
target getting stuck open

### ISSUE THREAD

**Issue by VizualDepzDev** [overextended/qtarget#61]
The tartget gets stuck open when attempting to interact with any motorcycle.

Default install no changes made.

https://cdn.discordapp.com/attachments/919294938087301191/941006434454343680/unknown.png

**Comment by meltynetv2** [comment]
> The tartget gets stuck open when attempting to interact with any motorcycle.
> 
> Default install no changes made.
> 
> https://cdn.discordapp.com/attachments/919294938087301191/941006434454343680/unknown.png

Same thing is happening for me with no edits, it seems to only happen on bicycles and motorcycles. It has to do with the bones system, not sure what is causing it though, maybe someone else can shed more light on how to fix this.

**Comment by JiminyKroket** [comment]
https://cdn.discordapp.com/attachments/926914270065737738/955886035462676620/unknown.png

The line required to edit is 225 as of 22/03/2022, the line edit is 
if data and next(data) then

https://cdn.discordapp.com/attachments/926914270065737738/955886541396406353/unknown.png

The fix will be in my PR to the system along with the CheckAllOptions function

**Comment by BerkieBb** [comment]
This should be fixed with V2.1.0
