### ISSUE TITLE
NOT an issue.. mechanically compatible with RedM ?

### ISSUE THREAD

**Issue by DocBurN** [overextended/qtarget#63]
Sorry to waste your time..  mechanically speaking is there anything that you know of that would prevent qtarget from working with the RedM platform.. ?

unless you already have a version/fork for it.. the redm forum yield no anwser so i came straight to the source... you..

You can close this "ticket".. thank you for your work..

**Comment by thelindat** [comment]
I don’t even have Red Dead to test with it, no clue.

**Comment by evanillaa** [comment]
@BerkieBb

**Comment by DocBurN** [comment]
Thank you.. i'll start adapting it..
