### ISSUE TITLE
[Bug] Issue with distance on vehicle bones

### ISSUE THREAD

**Issue by benzon** [overextended/qtarget#71]
https://user-images.githubusercontent.com/3528000/160656980-6dfe7cac-edc7-4609-85bd-18ba29b53b9f.mp4

So im having some issues with a distance bug and vehicle bones, added a video to showcase the issue.

**Comment by BerkieBb** [comment]
Oh that's back, I'll fix that later today

**Comment by benzon** [comment]
Sounds good!

@BerkieBb the PR thats hanging where he used _ indsted of changing to K is that something you could add to, since i actually think it's a very good idea, even tho it maybe should show up on a bit further distance then the distance of the eye it self.

**Comment by BerkieBb** [comment]
Fixed the issue

**Comment by benzon** [comment]
Ill test in just abit
