### ISSUE TITLE
error

### ISSUE THREAD

**Issue by stephen9898** [overextended/qtarget#73]
exports["qtarget"]:AddTargetModel({name = "EcolaMachine",label = "eCola Machine",icon = "fas-fa-wine-bottle",model = 992069095,interactDist = 5.0,onInteract = onInteract,options = options})
this expo wont work its giving me errors https://prnt.sc/vI5NzF_6yVYz

**Comment by N-fire** [comment]
Read the documentation, you are doing this completely wrong
https://overextended.github.io/qtarget/model

**Comment by stephen9898** [comment]
so can you help me as this was a paid script

**Comment by N-fire** [comment]
what qtarget is not a paid script

**Comment by stephen9898** [comment]
no the vending mechine i bought is

**Comment by stephen9898** [comment]
exports.qtarget:AddTargetModel(-654402915, name = "candyMachine",label = "Vending Machine",icon = "fas-fa-candy-cane",interactDist = 5.0,onInteract = onInteract,options = options)

**Comment by stephen9898** [comment]
should this way work

**Comment by N-fire** [comment]
no read the documentation

**Comment by stephen9898** [comment]
i dont under stand it

**Comment by BerkieBb** [comment]
The documentation provides enough information for you to understand what to do, please read it thoroughly
