### ISSUE TITLE
Target player

### ISSUE THREAD

**Issue by mistr140** [overextended/qtarget#77]
Is it possible to do it via qtarget so that the action always goes to the marked player? So that there is no local on the nearest player but on the player who was marked via the target.

My code:
![obrazek](https://user-images.githubusercontent.com/43046423/163581427-2e6b0381-91a6-4464-a4ab-6422d12f7a18.png)

**Comment by BerkieBb** [comment]
The entity which you target gets sent in the table that gets sent with the event arguments
