### ISSUE TITLE
Issue with ESX Item Recognision

### ISSUE THREAD

**Issue by TrymTube** [overextended/qtarget#81]
So I have installed qtarget today on my Server to give normal users without job acces to search and cuff players. But I for the cuff and uncuff method I need an Item. Once I join the Server with zipties ( Item I need ) I am able to cuff somebody but when I remove the Item from my inventory without reconnecting I am still able to cuff players same when I connect without cuffs and I buy some cuffs I cant handcuff people without reconnecting

**Comment by BerkieBb** [comment]
What inventory do you use?

**Comment by TrymTube** [comment]
normal esx_inventoryhud with esx_inventoryhud_trunk
