### ISSUE TITLE
Small bugs with latest source code

### ISSUE THREAD

**Issue by meltynetv2** [overextended/qtarget#82]
Hello, not sure if this is a bug or what not, but it definitely doesn't seem right to me. When I try to target a vehicle, the bones are very weird. Sometimes it will select one bone and then the next time it will select another bone on a vehicle without changing the position of the target, ped, and vehicle. As well it seems to duplicate some options 2-3 times when you target and untarget fast. And further more it seems to be selecting the "boot" bone when I am obviously selecting the front doors/whole vehicle(could be the vehicle, but it happens on all cars from what I can notice, but could be wrong).

Here are two examples of what I am speaking of. I am using the latest release with ESX-Legacy.

- https://i.gyazo.com/3ef6cd3777ac453ef032a56c0f48eb70.mp4
- https://i.gyazo.com/3203621cc9c9a71e5551650079965960.mp4

The vehicle used in the example is a in-game car called the Raiden, but is not limited to just the Raiden, seems to happen on most if not all cars now( custom added or in-game).

If some light can be shed on this, or if it is a bug can be fixed it would be great! If you need anything tested or more information, please do not hesitate to ask or let me know! Thanks for taking a look at this!

**Comment by BerkieBb** [comment]
Can you try downloading the source code?

**Comment by meltynetv2** [comment]
> Can you try downloading the source code?

What do you mean? Are you talking about downloading the github directly instead of the release? Let me know.

**Comment by meltynetv2** [comment]
> Can you try downloading the source code?

Okay, so yes I saw that one of the files was updated 12 days ago with a fix for duplication! I tried it, it works. Although there are many more problems that I have run into with this build. 

First when enabling sprites to appear on PolyZones, when clicking it it does not bring your cursor up or allow you to select any options for that PolyZone.

Second, when targeting the vehicle at certain angles and or generic angles it sometimes does the spas out thing still which can be seen here:
https://i.gyazo.com/9bb2b7d7197717df8dc641186f823974.mp4

Third, sometimes when trying to target something and you don't get it right away and you spam it kinda, it will keep the eye on the screen without targeting anything as seen here:
https://i.gyazo.com/5dbb9d17473ae13f550d412275604c87.mp4

Fourth, I do not get vehicle target options when I am looking at a bone of the vehicle, although I do not think this is a bug, just the way it is setup? You can see it here:
https://i.gyazo.com/97a1e3a95bfc84042229d855ea57c0b7.mp4

That is basically all that I am having an issue with right now with the source code download. Let me know if you need any more testing :) Just looking to help and get these fixed.

**Comment by thelindat** [comment]
I'm very much OOTL on the state of qtarget; is this something that still needs to be resolved before a final release and archiving the repo? @BerkieBb

**Comment by BerkieBb** [comment]
I'd rather archive qtarget noq and help with ox_target

**Comment by thelindat** [comment]
Bones have been forever janky as hell with qtarget, and it looks to me like options are also being registered multiple times or something here (registering in loops?). Not really something that can be fixed with this resource.
